Repository KOSA-ToT/tiary, pull requests merged in 2023-12, with the labels that each got.

#1 feature/SCRUM-17--Article
  server/src/main/java/com/example/tiary/TiaryApplication.java
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/dto/request/RequestArticleDto.java
  server/src/main/java/com/example/tiary/article/dto/response/ResponseArticleDto.java
  server/src/main/java/com/example/tiary/article/entity/Article.java
  server/src/main/java/com/example/tiary/article/entity/ArticleHashtag.java
  server/src/main/java/com/example/tiary/article/entity/Hashtag.java
  server/src/main/java/com/example/tiary/article/repository/ArticleHashtagRepository.java
  server/src/main/java/com/example/tiary/article/repository/ArticleRepository.java
  server/src/main/java/com/example/tiary/article/repository/HashtagRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/HashtagService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/article/service/impl/HashtagServiceImpl.java
  server/src/main/java/com/example/tiary/global/audit/AuditingFields.java
Labels: 💻개발, ⌨️BE

#3 feature/SCRUM-54--Hashtag
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/dto/response/ResponseArticleDto.java
  server/src/main/java/com/example/tiary/article/dto/response/ResponseHashtagDto.java
  server/src/main/java/com/example/tiary/article/entity/ArticleHashtag.java
  server/src/main/java/com/example/tiary/article/repository/ArticleHashtagRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
Labels: 💻개발, ⌨️BE

#12 [SCRUM-85] chore: 뷰 프로젝트 생성 및 세팅
  .gitignore
  client/.env.example
  client/README.md
  client/index.html
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/images/spring.jpg
  client/src/App.vue
  client/src/assets/base.css
  client/src/assets/logo.svg
  client/src/assets/main.css
  client/src/components/HelloWorld.vue
  client/src/components/TheWelcome.vue
  client/src/components/WelcomeItem.vue
  client/src/components/icons/IconCommunity.vue
  client/src/components/icons/IconDocumentation.vue
  client/src/components/icons/IconEcosystem.vue
  client/src/components/icons/IconSupport.vue
  client/src/components/icons/IconTooling.vue
  client/src/main.js
  client/src/pages/index.md
  client/src/router/index.js
  client/src/stores/index.md
  client/src/utils/index.md
  client/vite.config.js
Labels: 🖥️FE

#22 Feature/scrum 92 batch
  batch/build.gradle
  batch/gradle/wrapper/gradle-wrapper.properties
  batch/gradlew
  batch/gradlew.bat
  batch/settings.gradle
  batch/src/main/java/com/example/batch/BatchApplication.java
  batch/src/main/java/com/example/batch/article/controller/ArticleController.java
  batch/src/main/java/com/example/batch/article/dto/ArticleDto.java
  batch/src/main/java/com/example/batch/article/dto/ResponseArticleDto.java
  batch/src/main/java/com/example/batch/article/dto/ResponseRelatedArticleDto.java
  batch/src/main/java/com/example/batch/article/entity/Article.java
  batch/src/main/java/com/example/batch/article/entity/ArticleHashtag.java
  batch/src/main/java/com/example/batch/article/entity/ExtractKeyword.java
  batch/src/main/java/com/example/batch/article/entity/RelatedArticle.java
  batch/src/main/java/com/example/batch/article/repository/ArticleRepository.java
  batch/src/main/java/com/example/batch/article/repository/ExtractKeywordRepository.java
  batch/src/main/java/com/example/batch/article/service/ArticleService.java
  batch/src/main/java/com/example/batch/article/service/CacheService.java
  batch/src/main/java/com/example/batch/article/service/ExtractKeywordService.java
  batch/src/main/java/com/example/batch/article/service/KeywordAndSimilarityService.java
  batch/src/main/java/com/example/batch/article/service/MidnightCacheRefresh.java
  batch/src/main/java/com/example/batch/article/service/RecommendationService.java
  batch/src/test/java/com/example/batch/BatchApplicationTests.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/comment/entity/Comment.java
  server/src/main/java/com/example/tiary/global/batch/BatchRestTemplateConfig.java
  server/src/main/java/com/example/tiary/global/batch/BatchService.java
Labels: 💻개발, ⌨️BE

#25 Refresh Token 구현
  server/src/main/java/com/example/tiary/global/config/SpringSecurityConfig.java
  server/src/main/java/com/example/tiary/global/config/jwt/JwtAuthenticationFilter.java
  server/src/main/java/com/example/tiary/global/config/jwt/JwtAuthorizationFilter.java
  server/src/main/java/com/example/tiary/global/config/jwt/JwtProperties.java
  server/src/main/java/com/example/tiary/global/config/jwt/TokenService.java
  server/src/main/java/com/example/tiary/global/util/CookieUtil.java
Labels: ⌨️BE

#26 [SCRUM-95] HOME 화면 간단 구현
  client/index.html
  client/src/App.vue
  client/src/assets/css/font-awesome.min.css
  client/src/assets/css/main.css
  client/src/assets/fonts/FontAwesome.otf
  client/src/assets/fonts/fontawesome-webfont.eot
  client/src/assets/fonts/fontawesome-webfont.svg
  client/src/assets/fonts/fontawesome-webfont.ttf
  client/src/assets/fonts/fontawesome-webfont.woff
  client/src/assets/fonts/fontawesome-webfont.woff2
  client/src/assets/images/bg.jpg
  client/src/assets/images/dog.jpg
  client/src/assets/images/pic01.jpg
  client/src/assets/images/pic02.jpg
  client/src/assets/images/pic03.jpg
  client/src/assets/images/pic04.jpg
  client/src/assets/images/slide01.jpg
  client/src/assets/images/slide02.jpg
  client/src/assets/images/slide03.jpg
  client/src/assets/images/slide04.jpg
  client/src/assets/images/slide05.jpg
  client/src/assets/main.css
  client/src/components/Band.vue
  client/src/components/Card.vue
  client/src/components/Footer.vue
  client/src/components/Thumbnails.vue
  client/src/pages/Home.vue
  client/src/router/index.js
Labels: 🖥️FE

#28 [SCRUM-62] fix: 스프링 시큐리티 인증/인가 문제 해결
  server/src/main/java/com/example/tiary/global/config/jwt/JwtAuthorizationFilter.java
  server/src/main/java/com/example/tiary/global/config/jwt/TokenService.java
  server/src/main/java/com/example/tiary/global/util/CookieUtil.java
Labels: 🛠️bug

#29 Feature/scrum 108 article front
  client/src/App.vue
  client/src/components/ArticlePost.vue
  client/src/components/Category.vue
  client/src/components/Slider.vue
  client/src/pages/ArticleList.vue
  client/src/pages/Home.vue
  client/src/router/index.js
  server/gradle/wrapper/gradle-wrapper.properties
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/controller/HashtagController.java
  server/src/main/java/com/example/tiary/article/dto/request/RequestArticleDto.java
  server/src/main/java/com/example/tiary/article/dto/response/ResponseHashtagDto.java
  server/src/main/java/com/example/tiary/article/repository/HashtagRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/HashtagService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/article/service/impl/HashtagServiceImpl.java
  server/src/main/java/com/example/tiary/category/controller/CategoryController.java
  server/src/main/java/com/example/tiary/category/service/CategoryService.java
  server/src/main/java/com/example/tiary/category/service/impl/CatecoryServiceImpl.java
  server/src/main/java/com/example/tiary/global/config/CorsConfig.java
  server/src/main/java/com/example/tiary/global/config/SpringSecurityConfig.java
  server/src/main/java/com/example/tiary/global/s3/controller/S3Controller.java
  server/src/main/java/com/example/tiary/global/s3/service/ArticleImageService.java
  server/src/main/java/com/example/tiary/global/s3/service/S3UploadService.java
  server/src/main/java/com/example/tiary/myPage/service/impl/UserServiceImpl.java
Labels: 💻개발, 🖥️FE, ♻️refactoring, ⌨️BE

#32 Feature/scrum 108 article front
  batch/src/main/java/com/example/batch/article/controller/ArticleController.java
  batch/src/main/java/com/example/batch/article/service/ArticleService.java
  batch/src/main/java/com/example/batch/article/service/KeywordAndSimilarityService.java
  batch/src/main/java/com/example/batch/article/service/RecommendationService.java
  client/src/App.vue
  client/src/components/Category.vue
  client/src/components/Recommendations.vue
  client/src/components/Slider.vue
  client/src/components/article/ArticleCreate.vue
  client/src/components/article/ArticleEdit.vue
  client/src/components/icons/IconCommunity.vue
  client/src/components/icons/IconDocumentation.vue
  client/src/components/icons/IconEcosystem.vue
  client/src/components/icons/IconSupport.vue
  client/src/components/icons/IconTooling.vue
  client/src/pages/ArticleList.vue
  client/src/pages/Post.vue
  client/src/pages/index.md
  client/src/router/index.js
  client/src/stores/auth.js
  client/src/stores/index.md
  client/src/utils/dateformat.js
  client/src/utils/index.md
  server/src/main/java/com/example/tiary/article/controller/HashtagController.java
  server/src/main/java/com/example/tiary/article/entity/ArticleHashtag.java
  server/src/main/java/com/example/tiary/article/entity/ArticleImage.java
  server/src/main/java/com/example/tiary/article/entity/Hashtag.java
  server/src/main/java/com/example/tiary/article/repository/ArticleHashtagRepository.java
  server/src/main/java/com/example/tiary/article/service/HashtagService.java
  server/src/main/java/com/example/tiary/article/service/impl/HashtagServiceImpl.java
Labels: 💻개발, 🖥️FE, ♻️refactoring, ⌨️BE

#42 Feature/scrum 95 home
  client/src/assets/fonts/FontAwesome.otf
  client/src/assets/fonts/fontawesome-webfont.eot
  client/src/assets/fonts/fontawesome-webfont.svg
  client/src/assets/fonts/fontawesome-webfont.ttf
  client/src/assets/fonts/fontawesome-webfont.woff
  client/src/assets/fonts/fontawesome-webfont.woff2
  client/src/components/Band.vue
  client/src/components/Footer.vue
  client/src/components/Sidebar.vue
  client/src/components/Slider.vue
  client/src/components/home/Card.vue
  client/src/components/home/Member.vue
  client/src/components/home/TemplateCard.vue
  client/src/pages/Home.vue
Labels: 🖥️FE

#43 Feature/scrum 108 article front
  client/src/components/Header.vue
  client/src/components/NickNameCheckComp.vue
  client/src/components/article/ArticleCreate.vue
  client/src/components/article/ArticleEdit.vue
  client/src/pages/ArticleList.vue
  client/src/pages/VerifyEmail.vue
  client/src/stores/auth.js
  server/src/main/java/com/example/tiary/article/dto/response/ResponseArticleDto.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/global/s3/controller/S3Controller.java
  server/src/main/java/com/example/tiary/global/s3/service/S3UploadService.java
Labels: 🖥️FE, ♻️refactoring, ⌨️BE

#45 Feature/scrum 108 article front
  client/index.html
  client/src/App.vue
  client/src/components/Header.vue
  client/src/components/RandomArticle.vue
  client/src/components/Slider.vue
  client/src/components/Thumbnails.vue
  client/src/components/article/Article.vue
  client/src/pages/Home.vue
Labels: 🖥️FE, ♻️refactoring

#47 Feature/scrum 108 article front
  client/src/App.vue
  client/src/api/common.js
  client/src/components/Header.vue
  client/src/components/RandomArticle.vue
  client/src/components/Sidebar.vue
  client/src/components/article/Article.vue
  client/src/components/article/ArticleCreate.vue
  client/src/components/article/Recommendations.vue
  client/src/pages/ArticleList.vue
  client/src/pages/Home.vue
  client/src/router/index.js
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/repository/ArticleRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/global/config/jwt/JwtAuthorizationFilter.java
Labels: 🖥️FE, ♻️refactoring, ⌨️BE

#48 Feature/scrum 62 o auth2
  client/.env.example
  client/src/components/LoginOrReg.vue
  server/src/main/java/com/example/tiary/global/config/oauth/OAuth2UserCustomService.java
  server/src/main/java/com/example/tiary/global/config/oauth/Oauth2PrincipalDetails.java
  server/src/main/java/com/example/tiary/global/config/oauth/provider/NaverUserInfo.java
Labels: 💻개발, 🖥️FE, ⌨️BE

#50 Feature/scrum 25 user front
  client/package-lock.json
  client/package.json
  client/src/api/config.js
  client/src/components/Header.vue
  client/src/components/LoginOrReg.vue
  client/src/components/NickNameCheckComp.vue
  client/src/components/UserModal.vue
  client/src/pages/VerifyEmail.vue
  client/src/stores/auth.js
  client/src/utils/jwtUtils.js
Labels: 💻개발, 🖥️FE

#52 Feature/scrum 108 article front
  client/public/images/cat_1.jpg
  client/public/images/cat_2.jpg
  client/public/images/category.png
  client/public/images/cover.png
  client/public/images/editor_choice.png
  client/public/images/header_logo.png
  client/public/images/random_article.png
  client/src/components/Header.vue
  client/src/components/RandomArticle.vue
  client/src/components/Slider.vue
  client/src/components/article/Article.vue
  client/src/components/home/Card.vue
  client/src/components/home/Category.vue
  client/src/components/home/RandomArticle.vue
  client/src/components/home/TemplateCard.vue
  client/src/pages/Home.vue
Labels: 🖥️FE, ♻️refactoring

#53 Refactoring/scrum 116 article refactoring
  client/src/components/Sidebar.vue
  client/src/components/article/Article.vue
  client/src/components/article/Recommendations.vue
  client/src/components/home/Category.vue
  client/src/pages/ArticleList.vue
  server/src/main/java/com/example/tiary/article/controller/HashtagController.java
  server/src/main/java/com/example/tiary/article/dto/response/ResponseArticleDto.java
  server/src/main/java/com/example/tiary/article/repository/ArticleHashtagRepository.java
  server/src/main/java/com/example/tiary/article/repository/ArticleRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/HashtagService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/article/service/impl/HashtagServiceImpl.java
  server/src/main/java/com/example/tiary/category/controller/CategoryController.java
  server/src/main/java/com/example/tiary/global/pagination/PageInfo.java
  server/src/main/java/com/example/tiary/global/pagination/PageResponseArticleDto.java
  server/src/main/java/com/example/tiary/global/pagination/PaginationService.java
Labels: 🖥️FE, ♻️refactoring, ⌨️BE

#55 Feature/scrum 95 home
  client/public/images/book.svg
  client/public/images/comment-dots.svg
  client/public/images/heart.svg
  client/public/images/person-who-invests.svg
  client/public/images/slider1.png
  client/public/images/slider2.png
  client/public/images/slider3.png
  client/public/images/slider4.png
  client/public/images/slider5.png
  client/src/api/common.js
  client/src/components/Footer.vue
  client/src/components/Header.vue
  client/src/components/NickNameCheckComp.vue
  client/src/components/Sidebar.vue
  client/src/components/Slider.vue
  client/src/components/home/Card.vue
  client/src/pages/Home.vue
  client/src/pages/OauthCallback.vue
  client/src/router/index.js
  client/src/stores/auth.js
  client/src/utils/jwtUtils.js
  server/src/main/java/com/example/tiary/users/controller/UserController.java
Labels: 💻개발, 🖥️FE, ⌨️BE

#65 Feature/scrum 25 user front
  client/public/images/loading_1.gif
  client/src/components/Footer.vue
  client/src/components/LoginOrReg.vue
  client/src/components/Slider.vue
  client/src/components/UserModal.vue
  client/src/components/home/Card.vue
  client/src/components/home/Member.vue
  client/src/components/home/RandomArticle.vue
  client/src/components/myPage/myInfo.vue
  client/src/components/myPage/writerProfile.vue
Labels: 🖥️FE

#66 [SCRUM-112,113,114]-refactoring:프론트 다듬기,댓글 프로필 누르면 이동
  client/src/components/comment/Comment.vue
  client/src/components/comment/CommentCard.vue
  client/src/components/comment/ReplyCommentCard.vue
  client/src/components/myPage/myComment.vue
  client/src/components/myPage/myInfo.vue
  client/src/components/myPage/myPost.vue
  client/src/components/myPage/mySubscriber.vue
  client/src/components/myPage/postList.vue
  client/src/components/myPage/profile.vue
  client/src/components/myPage/writerProfile.vue
  server/src/main/java/com/example/tiary/comment/dto/response/CommentResponseDTO.java
  server/src/main/java/com/example/tiary/comment/service/CommentService.java
Labels: 🖥️FE, ♻️refactoring

#67 Refactoring/scrum 116 article refactoring
  client/src/api/common.js
  client/src/components/article/ArticleEdit.vue
  client/src/components/article/Recommendations.vue
  client/src/components/home/RandomArticle.vue
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
Labels: 🖥️FE, ♻️refactoring

#70 Feature/scrum 136 article fix refactoring
  client/src/api/common.js
  client/src/api/config.js
  client/src/components/article/Article.vue
  client/src/components/article/ArticleCreate.vue
  client/src/components/article/ArticleEdit.vue
  client/src/components/article/Recommendations.vue
  client/src/pages/ArticleList.vue
  client/src/pages/Home.vue
Labels: 🖥️FE, ♻️refactoring

#71 Refactor/scrum 81 user refactoring
  client/src/components/Sidebar.vue
  server/src/main/java/com/example/tiary/global/config/oauth/OAuth2FailureHandler.java
  server/src/main/java/com/example/tiary/global/config/oauth/OAuth2SuccessHandler.java
  server/src/main/java/com/example/tiary/global/config/oauth/OAuth2UserCustomService.java
Labels: ♻️refactoring

#72 Feature/scrum 136 article fix refactoring
  client/src/api/common.js
  client/src/components/article/Article.vue
  client/src/components/article/AuthorProfile.vue
  client/src/components/article/Recommendations.vue
  client/src/components/article/like/Like.vue
  server/src/main/java/com/example/tiary/article/controller/LikeController.java
  server/src/main/java/com/example/tiary/article/repository/ArticleLikesRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleLikesService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleLikesServiceImpl.java
  server/src/main/java/com/example/tiary/global/config/SpringSecurityConfig.java
Labels: 🖥️FE, ♻️refactoring

#74 Feature/scrum 66 toss payment
  .gitignore
  README.md
  TIARY-001 (1).png
  client/package-lock.json
  client/package.json
  client/src/api/common.js
  client/src/api/config.js
  client/src/components/TossPayment.vue
  client/src/components/article/Article.vue
  client/src/components/article/AuthorProfile.vue
  client/src/pages/Post.vue
  client/src/router/index.js
  payment/build.gradle
  payment/gradlew
  payment/gradlew.bat
  payment/settings.gradle
  payment/src/main/java/com/example/payment/PaymentApplication.java
  payment/src/main/java/com/example/payment/toss/config/CorsConfig.java
  payment/src/main/java/com/example/payment/toss/config/TossPaymentConfig.java
  payment/src/main/java/com/example/payment/toss/contoller/TossController.java
  payment/src/main/java/com/example/payment/toss/dto/PaymentInfo.java
  payment/src/main/java/com/example/payment/toss/entity/TossPayment.java
  payment/src/main/java/com/example/payment/toss/repository/TossPaymentRepository.java
  payment/src/main/java/com/example/payment/toss/service/TossPaymentService.java
  payment/src/test/java/com/example/payment/PaymentApplicationTests.java
Labels: 💻개발, 🖥️FE, ⌨️BE

#78 Feature/scrum 86 admin
  client/.env.example
  client/src/api/common.js
  client/src/components/AdminSidebar.vue
  client/src/components/Header.vue
  client/src/components/Sidebar.vue
  client/src/components/admin/ManagementsTable.vue
  client/src/components/myPage/MySubscribePost.vue
  client/src/components/myPage/myInfo.vue
  client/src/components/myPage/profile.vue
  client/src/router/index.js
  payment/gradlew
  server/src/main/java/com/example/tiary/admin/controller/AdminController.java
  server/src/main/java/com/example/tiary/admin/entity/WriteApproval.java
  server/src/main/java/com/example/tiary/admin/service/AdminService.java
  server/src/main/java/com/example/tiary/article/repository/ArticleRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/myPage/controller/MyPageController.java
  server/src/main/java/com/example/tiary/myPage/repository/SubscribeRepository.java
  server/src/main/java/com/example/tiary/myPage/repository/UserRepository.java
  server/src/main/java/com/example/tiary/myPage/service/SubscribeService.java
  server/src/main/java/com/example/tiary/myPage/service/UserService.java
  server/src/main/java/com/example/tiary/myPage/service/impl/SubscribeServiceImpl.java
  server/src/main/java/com/example/tiary/myPage/service/impl/UserServiceImpl.java
  server/src/main/java/com/example/tiary/users/controller/UserController.java
  server/src/main/java/com/example/tiary/users/service/EmailService.java
Labels: 🖥️FE, ⌨️BE

#79 Feature/scrum 136 article fix refactoring
  client/public/images/article_default_1.jpeg
  client/public/images/article_default_10.jpeg
  client/public/images/article_default_2.jpeg
  client/public/images/article_default_3.jpeg
  client/public/images/article_default_4.jpeg
  client/public/images/article_default_5.jpeg
  client/public/images/article_default_6.jpeg
  client/public/images/article_default_7.jpeg
  client/public/images/article_default_8.jpeg
  client/public/images/article_default_9.jpeg
  client/src/components/article/ArticleCreate.vue
  client/src/components/article/ArticleEdit.vue
  client/src/components/article/like/Like.vue
  client/src/components/home/RandomArticle.vue
  client/src/pages/ArticleList.vue
  server/src/main/java/com/example/tiary/article/controller/ArticleController.java
  server/src/main/java/com/example/tiary/article/repository/ArticleRepository.java
  server/src/main/java/com/example/tiary/article/service/ArticleService.java
  server/src/main/java/com/example/tiary/article/service/impl/ArticleServiceImpl.java
  server/src/main/java/com/example/tiary/global/batch/BatchService.java
Labels: 📄 Docs, 🖥️FE, ♻️refactoring, ⌨️BE
